### PR TITLE
Add help documentation for rules and global requirements

### LINKED ISSUE #125: Add Tooltips and Help Text for Rules
UAT revealed that their is some ambiguity surrounding the meaning of rules and fields. Tooltips/help text would alleviate some of this ambiguity. 

Rules in particular need clarification. I.e. the global requirement "Maximum Units From Year(s)" could say "At most X units may be completed from courses in the chosen year levels".

### PR DESCRIPTION
**Pull request by j-selby**
Closes https://github.com/cass-degrees/CASS-Degrees-Code/issues/125

This PR implements a help button for all rules and global requirements. This has been implemented for programs, subplans and courses.

A popup was chosen here to make it easier to read larger pieces of help documentation (for which e.g. a tooltip would not work)

Screenshot:

screenshot-23_02_21_-_06_08_19

### CODE REVIEW

**Review by JackSekoranja — APPROVED** [review]
Looks good, happy for you to commit

**Comment by Daniel-Jang** [comment]
Keep in mind that by default, Chrome disables pop-ups and I had to manually enable them to see the pop-ups. Otherwise, happy with this.

**Review by Daniel-Jang — APPROVED** [review]

**Comment by j-selby** [comment]
These popups are implemented in HTML, so that seems that could be an issue. What did this block look like?

**Comment by Daniel-Jang** [comment]
> These popups are implemented in HTML, so that seems that could be an issue. What did this block look like?

With the pop-up blocked in Chrome settings, nothing happens when you click on the '?' symbol. Chrome doesn't appear to ask the user if they want to unblock it or anything.

**Comment by JackSekoranja** [comment]
I had the same issue as Daniel, but I fixed it by reseting the browser cache. Maybe that's what happened when you allowed popups?

**Comment by Daniel-Jang** [comment]
> I had the same issue as Daniel, but I fixed it by reseting the browser cache. Maybe that's what happened when you allowed popups?

Oh, it worked when I opened a new window after enabling pop-ups.

**Pull request merged**
