### PR TITLE
Create and register a folder that contains the CSS, img and js files

### PR DESCRIPTION
**Pull request by Daniel-Jang**
Refer to the original issue here for more information: https://github.com/cass-degrees/CASS-Degrees-Code/issues/38

### CODE REVIEW

**Review by JackSekoranja — APPROVED** [review]
Seems to work fine and html/css locations are mostly clear. It did throw an exception initially when I navigated to `/api/sample/`, but this resolved itself when I reran `python manage.py makemigrations` and `python manage.py migrate`

@Daniel-Jang Note that Git doesn't keep track of directories, so the _img_ and _js_ directories weren't included in the commit you added

**Comment by Daniel-Jang** [comment]
As Jack mentioned, turns out git doesn't add empty directories, so I added some placeholder files. When actual images and javascript files are added, please delete these placeholder files.

**Comment by JackSekoranja** [comment]
Deleting the files will update Git and delete the folders, so you'll have to do this AFTER adding a different file in the directory

**Review by j-selby — APPROVED** [review]
The conventional way to keep an otherwise empty directory is a `.gitkeep` file, but other than that, looks good!

**Pull request merged**
