### PR TITLE
Added feature to generate excel files for the courses report.

### PR DESCRIPTION
**Pull request by Daniel-Jang**
Original Issue: #377 

Created a simple button that generates the courses report excel file:
image

Excel output:
image

### CODE REVIEW

**Review by joshcbee — CHANGES_REQUESTED** [review]
Looks great and works mostly from what I can test. One small bug, is where there are courses with the same code but different names (e.g. arab6501) the subplan/plan dependency will get added for both where you have only entered one - i.e. add ARAB6501 in person, get:

image

**Comment by Daniel-Jang** [comment]
> Looks great and works mostly from what I can test. One small bug, is where there are courses with the same code but different names (e.g. arab6501) the subplan/plan dependency will get added for both where you have only entered one - i.e. add ARAB6501 in person, get:
> 
> image

The bug you pointed out isn't caused by the code in this branch, but rather, caused by the way we save courses in rules. This bug has been outlined in this issue: #397 

However, it was good for you to point it out, I have not noticed this before.

**Comment by joshcbee** [comment]
Since Aiden's push in #366, courses are stored in rules with code and name.

Still, same question applies as I put on #397 as to whether two courses with the same code should exist or if it's just an idiosyncracy of the list that CASS should remove.

**Comment by Daniel-Jang** [comment]
> Since Aiden's push in #366, courses are stored in rules with code and name.
> 
> Still, same question applies as I put on #397 as to whether two courses with the same code should exist or if it's just an idiosyncracy of the list that CASS should remove.

That's strange, I replicated the issue identified in #397 just yesterday, which includes Aiden's code. Am not sure whats wrong, will investigate.

**Comment by joshcbee** [comment]
Following client meeting - the expectation is that course codes should be unique. Happy to approve.

**Review by joshcbee — APPROVED** [review]

**Pull request merged**
