### PR TITLE
Unique Course Codes

### PR DESCRIPTION
**Pull request by Daniel-Jang**
Original Issue: #414 

Course codes are now unique and trying to create a new course with same course code results in an error:
image

### CODE REVIEW

**Comment by Daniel-Jang** [comment]
Is this error message fine? Or should it be changed to make it more user friendly?

**Review by j-selby — APPROVED** [review]
Looks fine, the description naming a model might be a little intuitive.

**Review by JackSekoranja — APPROVED** [review]
Personally I'd make a more basic error message (i.e. "A course with this code already exists"). Tested it and it works fine

**Comment by Daniel-Jang** [comment]
Okay, managed to change the error message like the following:
image


Will merge it in now.

**Pull request merged**
