### PR TITLE
Custom Text Rule Update

### LINKED ISSUE #438: Make Custom Text Rule Clearer
Recent UAT showed that the custom text rules are not clear. Currently it has the following behaviours:

> *Edit:* "Students must complete the following: [Text Box]"
> *View:* "[# Units] units from [Text Box]"
> *PDF:* "For [# Units] units: [Text Box]"

As you can see, this clearly doesn't work if [Text Box] = "24 units of exchange". Therefore, we need to make it clear what the user is typing.

UAT Link: https://docs.google.com/document/d/1eOsRcQOtWZSDc-dio8-Mni9_g6zNw3X5m_AzjxYiqk0

### PR DESCRIPTION
**Pull request by spencerj411**
closes #438.
This PR aims to make custom text rule (program subplan, view program, pdf program, view subplan) consistent and easier to understand.
**creating a program:**
image
**viewing a program:**
image
**program pdf:**
image

### CODE REVIEW

**Review by JackSekoranja — CHANGES_REQUESTED** [review]
Pretty close, but it looks like the units don't appear when using the `view` option. This can probably be fixed by changing from `{{ rule.units }}` to `{{ rule.unit_count }}`, but I haven't checked so I'm not sure

**Issue Screenshot:**
>Screen Shot 2019-10-10 at 8 46 34 pm

**Comment by spencerj411** [comment]
I think this bug existed outside of my PR. However, as it was an easy fix, I changed it. Good call.

**Review by JackSekoranja — APPROVED** [review]
Works well, happy for you to merge

**Review by aidengeorge97 — APPROVED** [review]
Looks good, happy for you to merge (assuming you resolve the merge conflict).

**Pull request merged**
