### PR TITLE
Change icons on homepage as per UAT

### LINKED ISSUE #120: Increase Size of Home Icon in Breadcrumbs
UAT revealed that some users found the small home icon at the top of the breadcrumbs to be a bit small. Making this icon slightly larger would make it easier for users to click and see, and allow them navigate the site more intuitively.

### LINKED ISSUE #121: Merge "Open Existing" and "Manage Courses" Into One "Manage" Heading
On the index home page there are currently two links that serve effectively the same purpose, "Open Existing" and "Manage Courses". These should be merged into one. Users seemed to prefer "Manage" as a heading.

### PR DESCRIPTION
**Pull request by j-selby**
Closes #121.

UAT showed that the icons on the homepage were potentially misleading, and a more general-purpose manage option was preferred.

fixed-index-icons

### CODE REVIEW

**Review by joshcbee — CHANGES_REQUESTED** [review]
Getting a misalignment at max size. Also just to clarify this closes #121 rather than #120. If we don't currently have a path to bulk-upload, it may also be good to change the 5th icon to link there.

image

**Comment by j-selby** [comment]
@joshcbee unable to replicate. What browser/OS? Both chrome and firefox work fine for me on windows.

**Comment by joshcbee** [comment]
Chrome, Windows 10

**Comment by KavsHub** [comment]
I get the same issue. I'm on Chrome version 74 on Windows 10
It's fine on firefox.
image

**Comment by JackSekoranja** [comment]
I'm getting the same issue mentioned above on Safari, but Chrome seems to work fine. Running OSX 10.13

**Review by KavsHub — APPROVED** [review]
The issue is fixed on chrome now. Happy for it to be merged. (Tested on Firefox and Edge too)

**Pull request merged**
