### PR TITLE
Fix deleting courses in lists from returning no error

### LINKED ISSUE #454: Course deletion doesn't check if courses are used in lists (Enquiry?)
Courses that are used in subplans or programs can't be deleted, but courses used in lists can still be deleted without any warning or failure. Is this an intentional design?

Example:
List with courses:
image

Courses page after attempting to delete all courses:
image

### PR DESCRIPTION
**Pull request by j-selby**
Closes #454.

Preview:
course-delete

### CODE REVIEW

**Review by spencerj411 — CHANGES_REQUESTED** [review]
When I create a course list within creating/editing a Program, and then I try to delete a subset of those courses after, an error pops up; looks good.

I'm still unsure about the case of creating/editing a List, and then when I try to delete a subset of those courses after, the deletion goes through. Is this intentional? Thanks.

**Comment by j-selby** [comment]
@spencerj411 I was unable to replicate your second issue:
- I created a list
- Added a course to it, saved it
- Attempted to delete that course, which failed

Do you have specific replication steps?

**Comment by spencerj411** [comment]
nvm, both cases look good.

**Review by spencerj411 — APPROVED** [review]

**Review by JackSekoranja — APPROVED** [review]
Worked for me, happy for you to merge

**Pull request merged**
