### PR TITLE
Implement custom checkboxes globally

### PR DESCRIPTION
**Pull request by j-selby**
This took *way* too long.

This PR implements themed checkboxes to improve clarity in the overall forms. The initial problem faced by this was that checkboxes *cannot* be styled by CSS in most browsers - they always use the platform checkbox, and that is all you get. The workaround, in this case, is to completely reimplement the rendering of checkboxes (using a library - not all in this PR!) and do that rendering ourselves.

The second issue is that this custom rendering approach requires additional elements around the checkbox to facilitate custom styling (again, noting that CSS doesn't allow for this). Django, however, doesn't allow for this by default when compositing forms - we would need custom logic for this, which I deemed too overkill for this.

In this PR therefore, I implement a custom JavaScript event handler on page loads which attempts to swap out any checkboxes it can find with styled ones, falling back gracefully if this is not possible. This doesn't work on Vue elements - these have to be manually styled.

Screenshot:

checkbox

### CODE REVIEW

**Review by JackSekoranja — APPROVED** [review]
It’s a shame there isn’t an easier way to do this but it does work. I did notice that the /staff/list page doesn’t render the special checkboxes but that should be okay since they’re not really supposed to be deleting courses anyway. Happy for you to merge

**Review by aidengeorge97 — CHANGES_REQUESTED** [review]
Looks good but it I'm getting some additional artefacts appearing on/around the boxes? This might just be my set up but I'd like to get your thoughts before I approve the PR.

Google Chrome:
image

Microsoft Edge:
image

**Review by spencerj411 — COMMENTED** [review]
I'm also experiencing what Aiden got
**On Google Chrome:**
image

**Comment by j-selby** [comment]
Issues with Chrome/Edge should now be fixed - they were both behaving weirdly when dealing with overflow.

**Review by aidengeorge97 — APPROVED** [review]
Those changes seem to have fixed it. Happy to approve now.

**Pull request merged**
