### PR TITLE
MVP Completion

### PR DESCRIPTION
**Pull request by Daniel-Jang**
Please refer to this old PR for reference, and please read my last comment regarding the remaining issues for MVP.

https://github.com/cass-degrees/CASS-Degrees-Code/pull/170

### CODE REVIEW

**Comment by Daniel-Jang** [comment]
Also, should we add release notes to this branch? A simple text file that summaries the features in this MVP (or maybe just a simple link).

**Comment by Daniel-Jang** [comment]
I will be going through this "Django deployment checklist" (https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/) so stay tuned for updates to this release branch.

**Comment by j-selby** [comment]
Just saw your comments - might make more sense to just use Git tags to represent releases rather than branches?

**Comment by Daniel-Jang** [comment]
> Just saw your comments - might make more sense to just use Git tags to represent releases rather than branches?

I thought so too, but that means we won't be able to make any changes to the develop branch until MVP is merged in to master, which will hold us back from doing work that is for post MVP (e.g. this semester's work). 

We also have to make modifications to the Django configuration so that it is ready for deployment (disable debugging, add release notes etc) that we don't want to do on our develop branch. 

This method is also mentioned in the Git Branching method document.

**Comment by Daniel-Jang** [comment]
Just an update, settings.py has been modified to make sure the developer takes a look before deploying the website. Updates were pushed 3 days ago but I have forgotten to mention it here.

**Comment by Daniel-Jang** [comment]
Ok, added a checklist for server deployment in SETUP.md, implemented Josh's fix to the edit problems and fixed all the pep 8 violations where sensible. 

This is ready for review now.

**Comment by Daniel-Jang** [comment]
Upon discussion with the team on 21/8/19, this branch is approved to be pushed into the master branch, and we will simply improve it by releasing subsequent versions.

**Pull request merged**
