### PR TITLE
Bulk Data Upload

### PR DESCRIPTION
**Pull request by Daniel-Jang**
This feature allows courses and subplans to be added in bulk: https://github.com/cass-degrees/CASS-Degrees-Code/issues/28
image

Example Files here for reference:
[subplans.txt](https://github.com/cass-degrees/CASS-Degrees-Code/files/3085295/subplans.txt)
[courses.txt](https://github.com/cass-degrees/CASS-Degrees-Code/files/3085296/courses.txt)

### CODE REVIEW

**Comment by j-selby** [comment]
I'm not sure we completely resolved this one - did we get info on what kinds of data the client might want to be uploading? e.g. format here is not csv but percent delimited.

**Comment by JackSekoranja** [comment]
Yeah, I talked to Daniel about this and since the data we have seen didn’t have any structure it’s likely they will use it by generating the data specifically for the purpose of putting it in this system. That in addition to the fact that courses can have commas made us think that it was still reasonable to complete it as a TSV. Plus if this is available it opens the door to automation and other kinds of things - long story short as long as we can mass read in data in some form it’s still useful to the clients

**Comment by Daniel-Jang** [comment]
Also James, this commit added explanations on why '%' was used instead of commas: https://github.com/cass-degrees/CASS-Degrees-Code/pull/66/commits/76e642527a05084ef9ffc48f6841e3c8ffc41a0c

Delimiter can be easily changed to something else if necessary
Jack did mention TSV since that's what I told him at the time and can be easily changed to that again.

**Review by JackSekoranja — APPROVED** [review]
Tested and looks good. I would have preferred you link it to the main menu somehow but I understand that may be outside of scope for the user story.

**Pull request merged**
