### PR TITLE
Feature program subject area changes

### LINKED ISSUE #437: Replace "X units of [Subject Code]" with "X units of [Subject Area]"
ANU Colleges are not allowed to specify in programs “Complete X units of ARTS subject area”. Those who do (Like CECS 🙂) have not read the policies properly. It should instead say “Complete X units of Arts Courses”. After reviewing this, I think the best way of implementing this functionality is to use a plain text field that will be displayed in view and PDF.

UAT Link: https://docs.google.com/document/d/1eOsRcQOtWZSDc-dio8-Mni9_g6zNw3X5m_AzjxYiqk0/edit#

### PR DESCRIPTION
**Pull request by spencerj411**
closes #437.

Changes include:

- replacing select menu to textbox in global requirements and course elective rules
- added onkeydown check to the textbox to ensure users are only inputting letters and spaces
- replaced default value from 'any' to '' (global requirements)
- replaced default value from 'all' to '' (course elective)
- validation error message
- updated View to accommodate for the new changes
- updated PDF to accommodate for the new changes
image
image

### CODE REVIEW

**Review by JackSekoranja — CHANGES_REQUESTED** [review]
Doesn't seem to translate as gracefully in to PDFs and Courses as it should. See below:

**PDF:**
Screen Shot 2019-10-10 at 8 51 41 pm

**View:**
Screen Shot 2019-10-10 at 8 52 21 pm

Screen Shot 2019-10-10 at 8 52 28 pm

**Comment by spencerj411** [comment]
My bad. These are the changes to global requirements (will add changes to course electives in a moment)
**Creating/Editing Program:**
Note: ignore size of arrows as I zoomed out to 50% to take the screenshot.
image
**Viewing Program:**
image
**Generating Program PDF:**
image

**Comment by spencerj411** [comment]
Changes for Course Electives (plus Either Or)
Note: Either Or Course (View) was not fully implemented before.
**Creating/Editing Program (Course Elective Rule):**
image
**Creating/Editing Program (Course Elective Either Or Rule):**
image
**Viewing a Program:**
image
**Generating a PDF Program:**
image

**Review by JackSekoranja — APPROVED** [review]
Looks good, happy for you to merge now

**Pull request merged**
