### PR TITLE
Rule and Or Group reordering Take 2

### PR DESCRIPTION
**Pull request by Daniel-Jang**
Original PR: #411 
Original Issue: #379 

This Pull Request allows the user to move rules and or group rules up and down. The code is based on James' refactoring branch.

View:
image

### CODE REVIEW

**Review by j-selby — APPROVED** [review]
Everything looks good for this one, but is it possible to hide the move up/down buttons if the item in question is already the top/bottom element respectively?

**Comment by JackSekoranja** [comment]
I still think this should allow users to place rules into/out of OR rules, as that was what the tester was actually referring to when they raised the issue

**Comment by Daniel-Jang** [comment]
> Everything looks good for this one, but is it possible to hide the move up/down buttons if the item in question is already the top/bottom element respectively?

It is possible, but it would require a bit of extra javascript and I'm not sure how to go about with it. Also, I don't think the extra effort required to make it work is worth the gains, in my opinion. Thanks for the suggestion though.

**Comment by Daniel-Jang** [comment]
> I still think this should allow users to place rules into/out of OR rules, as that was what the tester was actually referring to when they raised the issue

Hmm, maybe that should be another issue then? The users also wanted the ability to reorder things, which is what this PR addresses.

**Pull request merged**
