### PR TITLE
Implement student plan creation pipeline

### LINKED ISSUE #182: Start Creating Plan (8)
As a _Student_,
I want to be able to start creating a new plan,
So that I can determine an acceptable plan for my degree and graduate on time.

**Acceptance Criteria:**

- Creating a new plan does not affect existing plans

- Users are prompted to select their program once they create a new plan

**User Story Points:** 8

### PR DESCRIPTION
**Pull request by j-selby**
Depends on #211

Closes #182

This implements a landing page, a search page for programs as well as a placeholder edit page.

Search functionality was added using the pre-existing list.js implementation - its not perfect but is fairly decent.

Some placeholders for other bits and pieces was also added to demonstrate the workflow - they are mostly stubs and will need to be replaced later. See below screenshots.

Note that authentication (visible in the top right) is optional and isn't checked here (except for the 'Save and approve' button).

Landing page
Search page
Edit page

### CODE REVIEW

**Comment by j-selby** [comment]
(PIP issues not from this PR)

**Review by joshcbee — CHANGES_REQUESTED** [review]
Hey James, I'm getting an error with the hide details displaying (Chrome), picture below:
image

**Comment by j-selby** [comment]
@joshcbee I updated the static css stylesheet for this one - did you clear your cache?

**Comment by joshcbee** [comment]
@j-selby clearing the cache has resolved in with the changes, but now getting this on trying to load a shell program with one subplan worth 24 units

image

**Comment by j-selby** [comment]
@joshcbee this one should be fixed now

**Comment by joshcbee** [comment]
Looks good, James. Perhaps specify explicitly in the comments for those implementing later functionality that once an edit page is opened there should be a 'program' variable which is an instance of the chosen plan from which to extract requirements, but otherwise good to go.

**Review by joshcbee — APPROVED** [review]
As above re: commenting, but good to go!

**Review by JackSekoranja — APPROVED** [review]
Works well, would be happy for you to push

**Pull request merged**
