### PR TITLE
Tweak search logic on Student Planner

### LINKED ISSUE #236: Search functionality on the Program Planner Tool is underperforming
When searching the exact course codes, the course with the exact same code in question does not appear, while other courses appear. Additionally, multiple versions of courses are appearing, possibly because they have been assigned different years.

There might be issues with the fuzzy search, needs investigation.

### PR DESCRIPTION
**Pull request by j-selby**
Closes #236.

This PR tweaks search by importing a third party library (fuse.js) to improve search quality overall. All results are piped back into list.js as per normal.

Each field is searched individually now, and the search does do proper weighting of different fields.

The top 3 pages of results are displayed (unless the search algorithm chooses fewer). These are not sorted at this point in time due to list.js's sorting interface not behaving well.

### CODE REVIEW

**Review by JackSekoranja — APPROVED** [review]
Much better, nicely done. Happy for you to push

**Comment by JackSekoranja** [comment]
Actually the PR seems to have broken the homepage styling. Would appreciate a fix
Screen Shot 2019-08-28 at 1 47 32 pm

**Comment by j-selby** [comment]
@JackSekoranja ah, woops. Should be fixed now.

**Review by Daniel-Jang — APPROVED** [review]
Works far better than before, happy for it to be merged.

**Pull request merged**
