### PR TITLE
Subplan saving

### PR DESCRIPTION
**Pull request by JackSekoranja**
This pull request completes issue #26, and is a branch off of PR #71. It mostly adds a single boolean value to Subplan forms that represents whether it should be published or not. However, it also modifies the database in preparation for the recursive rules structure as outlined in #72, and I have verified that JSON objects correctly get saved in the 'rules' field

### CODE REVIEW

**Comment by KavsHub** [comment]
Merged and resolved conflicts for you :D

**Review by KavsHub — APPROVED** [review]
Looks good. As mentioned before I merged the conflicts all ready for you.

**Review by Daniel-Jang — APPROVED** [review]
Seems pretty simple and neat to me, I don't see any problems from my end.

**Comment by JackSekoranja** [comment]
Closed due to changes in approach

**Pull request closed without merging**
