### PR TITLE
MVP Completion

### PR DESCRIPTION
**Pull request by JackSekoranja**
This PR implements all the features specified in the MVP, in addition to authentication features.

### CODE REVIEW

**Review by Daniel-Jang — APPROVED** [review]

**Comment by j-selby** [comment]
Blocked by remaining issues in https://github.com/cass-degrees/CASS-Degrees-Code/projects/1

**Comment by j-selby** [comment]
No outstanding issues remain in Git for this.

**Comment by Daniel-Jang** [comment]
UPDATE: I will merge this to Develop once the current UAT related issues are completed.

**Comment by j-selby** [comment]
Now only depends on #161, #110

**Comment by Daniel-Jang** [comment]
Are we still waiting for issues mentioned by Jack? 
Both of them are removed from MVP but I am not sure if the people who were assigned these tickets are still working on them. 

Also, I checked the git branching document:
https://docs.google.com/document/d/1whU7j2F_0RFJ1n1rJsn3H6UcKvLCPCmKZ2J65a7D-9g/edit
and I noticed that we should be creating a new branch specific for release only, instead of pulling directly from develop to master. I will close this PR request and create a new release branch for all the commits up to now. I will then create a new pull request from that release branch and link this PR.

**Pull request closed without merging**
