### PR TITLE
Enable the rendering of student plans as PDFs

### LINKED ISSUE #207: Export Plan as PDF (13)
As a _Student/CASS Staff Member_,
I want to be able to save a complete plan as a PDF,
So that I can keep a record of it and take a copy of the plan to a session.

**Acceptance Criteria:**

- The application can convert program plans into a readable PDF format
- There exists a button to generate a PDF from the currently open plan
- Students and Staff can save or print the PDF after it has been generated

**User Story Points:** 13

### PR DESCRIPTION
**Pull request by j-selby**
Closes #207.

This PR adds a button to the student homepage to render their plan as a PDF. The plan will be saved before the PDF is rendered. The pipeline is a modified one from staff's PDF rendering, with changes to (the render) environment and how course boxes are rendered.

Global requirements aren't validated yet as this is still to be implemented in the frontend. This will likely need to be stored in the main plan object when that is implemented for this to work.

student-pdf

### CODE REVIEW

**Review by JackSekoranja — CHANGES_REQUESTED** [review]
It works, I have a blank page between one of my elements. I have attached the elements on the first and third pages. It would be good if you could prevent this split from happening.

Screen Shot 2019-08-25 at 3 59 25 pm

Screen Shot 2019-08-25 at 3 58 04 pm

**Comment by j-selby** [comment]
@JackSekoranja that was intentional iirc - this is the same styling from the staff frontend. I can change it if needed

EDIT: Oh, a blank page? Yeah, thats a bug. let me check.

**Comment by j-selby** [comment]
@JackSekoranja that should be fixed now.

**Review by JackSekoranja — APPROVED** [review]
Okay, happy for you to push. We just need to make sure that when we add subplan functionality this still works

**Review by Daniel-Jang — APPROVED** [review]
It appears to work well for me, approved.
As you have mentioned previously, this PR plays well with the subplan rules section.

**Pull request merged**
