### PR TITLE
Feature main menu and navigation

### PR DESCRIPTION
**Pull request by joshcbee**
Implemented basic splash screen as per wireframe and styling template. Navigation will be implemented separately, but the main menu should allow the progression of other basic user stories (e.g. create plan/subplan etc.

### CODE REVIEW

**Comment by Daniel-Jang** [comment]
I had a look and noticed that the menu directly links to the Django REST API. Is this temporary? Because in our final product, our website should not be showing the Django REST APIs directly to the user. If this is temporary, I'm happy to approve it.

Looks like there there are some merge issues due to my branch. I will fix the git merge issues so take a look later in the day to see if I messed up anything. :)

**Comment by joshcbee** [comment]
CASS Degrees Main Menu (2)


Screenshot main menu

**Review by JackSekoranja — APPROVED** [review]
Works well as a temporary solution, but we might want to polish it up later (i.e. use higher-res images, ensure no copyright issues, link actual pages, etc.). Found no issues in the code itself

**Review by Daniel-Jang — APPROVED** [review]

**Comment by joshcbee** [comment]
Links to REST API are temporary, to be updated as actual pages become available.
Will polish up later with higher-res images, images are custom/material design icons, so should be no copyright issues, but will confirm.

**Pull request merged**
