### PR TITLE
Minimum Maximum Course Rule Option

### LINKED ISSUE #350: Course rule needs to support "At least X but no more than Y" cases
At the end of the UAT with Beth, she pointed out that there are some programs that contains course lists that said "At least X but no more than Y" courses. We currently do not have a way to represent this, so we should add support for such occurrences.

Example program with this: https://programsandcourses.anu.edu.au/2019/program/MLING

UAT Link: https://docs.google.com/document/d/1wk9sX77a6Vi7mha6BX23KsZodu_yuyDUunoW9eJvKIs/edit#

### PR DESCRIPTION
**Pull request by aidengeorge97**
Closes #350.

Enables CASS staff to represent course rules like below in the system.
image

Screenshot:
image

### CODE REVIEW

**Comment by j-selby** [comment]
Not directly related, but how would we compute overall units with this approach (i.e to verify that everything adds up at the end)?

**Comment by JackSekoranja** [comment]
> Not directly related, but how would we compute overall units with this approach (i.e to verify that everything adds up at the end)?

I already have a system for this. It basically sums up exact, minimum and maximum units in a dict (`{'exact': 0, 'min': 0, 'max': 0}`) and will accept it if the total unit count falls within this range. Still, there is a potential collision with #382

**Comment by aidengeorge97** [comment]
@Jack, will that system be compatible with what I've built here? I suppose you should be able to test if the course rule is a min_max and if so just add the min_units and max_units instead?

Although I am a little unsure how this rule fits in with an overall plan. I assume the minimum unit count is what is needed and counted towards the total, and the maximum unit count is just an extra constraint

**Comment by JackSekoranja** [comment]
Yeah it’s very easy. You should just be able to modify the ‘count_units’ function to be the same as the other one with Min/Max

**Comment by aidengeorge97** [comment]
Okay Jack, I've added that compatibility in. It counts the min_unit_count from min_max course rules.

**Comment by aidengeorge97** [comment]
I've rebased this to now be compatible with Jack's recent PR which implements unit count verification. I believe this PR is ready to be reviewed again after the discussions.

**Review by Daniel-Jang — CHANGES_REQUESTED** [review]
As long as the values are correct, it works fine. However, when the min is > max, hitting the 'save' or 'save and exit' provides no response, no error messages and stuff. I am happy to approve after this is fixed.

**Review by j-selby — CHANGES_REQUESTED** [review]
This seems to have issues with updating the UI (Firefox 71):

broken-uat-min-max

Adding a new course rule and setting min/max doesn't add the boxes until a redraw occurs.

Code otherwise looks fine!

**Review by Daniel-Jang — APPROVED** [review]
Ok turns out the error message only appears in programs. I am happy to approve it now but please ensure it appears for subplans before merging it in to develop.

**Comment by aidengeorge97** [comment]
> Adding a new course rule and setting min/max doesn't add the boxes until a redraw occurs.

I've just tested this with Firefox 69 and 71 and I wasn't able to recreate the issue you described. I'm confident that the dropdown should be causing a redraw because this was an issue I dealt with while developing the feature. Did you do a full ctrl-shift-r refresh? Or are you sure you're running the latest commit?

**Review by j-selby — APPROVED** [review]
Bug resolved. Looks good!

**Pull request merged**
